import {AVATARS,DECK,PHASES,REACTIONS,SCORING} from '../../config/game';
import {canHitOnCombination,findPhase,makeCombination,validatePhase,explainGroup,phaseProgress} from './validation';
import type {Action,Card,Game,Player,View} from './types';
export function shuffle<T>(items:T[]){const a=[...items];for(let i=a.length-1;i>0;i--){const max=0x100000000-(0x100000000%(i+1));let n;do{n=crypto.getRandomValues(new Uint32Array(1))[0];}while(n>=max);const j=n%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
export function createDeck():Card[]{const cards:Card[]=[];for(const color of DECK.colors)for(let n=DECK.min;n<=DECK.max;n++)for(let j=0;j<DECK.copies;j++)cards.push({id:`${color}-${n}-${j}`,color,value:n});for(let j=0;j<DECK.wilds;j++)cards.push({id:`wild-${j}`,color:'wild',value:0});return shuffle(cards);}
export function makePlayer(name:string,session:string,avatar=AVATARS[0],bot=false):Player{return {id:crypto.randomUUID(),session,name,avatar,hand:[],phase:0,completed:false,score:0,roundScore:0,lastSeen:Date.now(),bot};}
export function newGame(code:string,host:Player,demo=false):Game{return {code,status:'lobby',hostId:host.id,players:[host],deck:[],discard:[],groups:[],turn:0,step:'draw',round:0,version:0,createdAt:Date.now(),updatedAt:Date.now(),turnAt:Date.now(),timer:0,log:[],demo};}
export function log(g:Game,text:string){g.log.unshift({id:crypto.randomUUID(),text,at:Date.now()});g.log=g.log.slice(0,60);}
export function scoreHand(hand:Card[]){return hand.reduce((n,c)=>n+(c.color==='wild'?SCORING.wild:c.value>=SCORING.highStartsAt?SCORING.high:SCORING.low),0);}
export function beginRound(g:Game){g.round++;g.status='playing';g.deck=createDeck();g.discard=[];g.groups=[];g.step='draw';g.turn=(g.round-1)%g.players.length;g.turnAt=Date.now();for(const p of g.players){p.hand=g.deck.splice(-10);p.completed=false;p.roundScore=0;}let card=g.deck.pop()!;while(card.color==='wild'){g.deck.unshift(card);card=g.deck.pop()!;}g.discard=[card];log(g,`Round ${g.round}. Let’s play!`);}
function take(g:Game){if(!g.deck.length){if(g.discard.length<=1)throw new Error('No cards remain to draw.');const top=g.discard.pop()!;g.deck=shuffle(g.discard);g.discard=[top];}return g.deck.pop()!;}
function finishIfEmpty(g:Game,p:Player){if(p.hand.length)return;g.status='round-end';g.roundWinner=p.id;for(const x of g.players){x.roundScore=scoreHand(x.hand);x.score+=x.roundScore;if(x.completed)x.phase++;}const winners=g.players.filter(x=>x.phase>=PHASES.length).sort((a,b)=>a.score-b.score);if(winners.length){g.status='finished';g.winner=winners[0].id;g.finishedAt=Date.now();}log(g,`${p.name} went out! Round ${g.round} is complete.`);}
export function applyAction(source:Game,playerId:string,a:Action):Game{const g=structuredClone(source),p=g.players.find(p=>p.id===playerId);if(!p)throw new Error('Join this room to play.');p.lastSeen=Date.now();
if(a.type==='reaction'){if(!REACTIONS.includes(a.text??''))throw new Error('Choose one of the quick reactions.');if(p.reaction&&Date.now()-p.reaction.at<1000)throw new Error('Give that reaction a moment.');p.reaction={text:a.text!,at:Date.now()};}
else if(a.type==='add-bot'){if(g.hostId!==p.id||g.status!=='lobby')throw new Error('Only the host can add practice players in the lobby.');if(g.players.length>=6)throw new Error('All six seats are taken.');const i=g.players.length;g.players.push(makePlayer(['Clover','Cleo','Ollie','Pip','Leo','Fern'][i],`bot-${crypto.randomUUID()}`,AVATARS[i],true));}
else if(a.type==='settings'){if(g.hostId!==p.id||g.status!=='lobby')throw new Error('Only the host can change lobby settings.');if(![0,30,60,90].includes(a.timer!))throw new Error('Choose an available timer.');g.timer=a.timer!;}
else if(a.type==='start'||a.type==='next'||a.type==='rematch'){if(g.hostId!==p.id)throw new Error('The host starts the next round.');if(a.type==='start'&&(g.status!=='lobby'||g.players.length<2))throw new Error('You need at least two players to start.');if(a.type==='next'&&g.status!=='round-end')throw new Error('This round is still in play.');if(a.type==='rematch'){if(g.status!=='finished')throw new Error('Finish this game first.');for(const x of g.players){x.phase=0;x.score=0;}g.round=0;g.winner=undefined;g.finishedAt=undefined;g.createdAt=Date.now();}beginRound(g);}
else {if(g.status!=='playing')throw new Error('Wait for the next round to start.');if(g.players[g.turn].id!==p.id)throw new Error('It is not your turn yet.');if(a.version!==undefined&&a.version!==source.version)throw new Error('The table changed. Try your move again.');
if(a.type==='draw'){if(g.step!=='draw')throw new Error('You already drew. Play your phase or discard one card.');if(a.source==='discard'){if(!g.discard.length||g.discard.at(-1)!.color==='wild')throw new Error('Draw from the deck instead.');p.hand.push(g.discard.pop()!);log(g,`${p.name} picked up the discard.`);}else{p.hand.push(take(g));log(g,`${p.name} drew a card.`);}g.step='play';}
else {if(g.step!=='play')throw new Error('Start by drawing a card.');
if(a.type==='phase'){if(p.completed)throw new Error('You already completed your phase this round.');const groups=(a.groups??[]).map(ids=>ids.map(id=>{const c=p.hand.find(x=>x.id===id);if(!c)throw new Error('Choose cards from your own hand.');return c;}));if(!validatePhase(groups,p.phase)){const req=PHASES[p.phase].groups;const i=req.findIndex((r,i)=>explainGroup(groups[i]??[],r)!=='Ready to play');throw new Error(i>=0?explainGroup(groups[i]??[],req[i]):`Your objective is ${PHASES[p.phase].name.toLowerCase()}.`);}const played=new Set(groups.flat().map(c=>c.id));p.hand=p.hand.filter(c=>!played.has(c.id));g.groups.push(...groups.map((cards,i)=>makeCombination(cards,PHASES[p.phase].groups[i],p.id)));p.completed=true;log(g,`${p.name} completed phase ${p.phase+1}!`);finishIfEmpty(g,p);}
else if(a.type==='hit'){if(!p.completed)throw new Error('Complete your phase before adding to the table.');const c=p.hand.find(c=>c.id===a.cardId),group=g.groups.find(x=>x.id===a.groupId);if(!c||!group||!canHitOnCombination(c,group,a.side))throw new Error('That card does not fit here. Try another group or end of the run.');p.hand=p.hand.filter(x=>x.id!==c.id);if(group.kind==='run'){if(a.side==='start'){group.values.unshift(group.values[0]-1);group.cards.unshift(c);}else{group.values.push(group.values.at(-1)!+1);group.cards.push(c);}}else{group.cards.push(c);group.values.push(c.value);}log(g,`${p.name} added a card to a ${group.kind}.`);finishIfEmpty(g,p);}
else if(a.type==='discard'){const c=p.hand.find(c=>c.id===a.cardId);if(!c)throw new Error('Select one card to discard.');p.hand=p.hand.filter(x=>x.id!==c.id);g.discard.push(c);log(g,`${p.name} discarded ${c.color==='wild'?'a wild':`a ${c.color} ${c.value}`}.`);finishIfEmpty(g,p);if(g.status==='playing'){g.turn=(g.turn+1)%g.players.length;g.step='draw';g.turnAt=Date.now();}}
else throw new Error('That action is not available.');}}
g.version++;g.updatedAt=Date.now();return g;}
export function publicView(g:Game,session:string):View{const me=g.players.find(p=>p.session===session);const {deck,discard,players,...rest}=g;return {...rest,players:players.map(({session,hand,lastSeen,...p})=>({...p,handCount:hand.length,connected:p.bot||Date.now()-lastSeen<35000})),deckCount:deck.length,topDiscard:discard.at(-1)??null,hand:me?.hand??[],me:me?.id??null};}
export function getValidMoves(g:Game,playerId:string){const p=g.players.find(p=>p.id===playerId);if(!p||g.status!=='playing'||g.players[g.turn].id!==playerId)return [];if(g.step==='draw')return [{type:'draw',source:'deck'},...(g.discard.at(-1)?.color!=='wild'&&g.discard.length?[{type:'draw',source:'discard'}]:[])];const moves:Action[]=p.hand.map(c=>({type:'discard',cardId:c.id}));if(!p.completed){const groups=findPhase(p.hand,p.phase);if(groups)moves.push({type:'phase',groups:groups.map(g=>g.map(c=>c.id))});}else for(const c of p.hand)for(const group of g.groups)for(const side of ['start','end'] as const)if(canHitOnCombination(c,group,side))moves.push({type:'hit',cardId:c.id,groupId:group.id,side});return moves;}
export function botTurn(g:Game):Game{const p=g.players[g.turn];let next=g;if(g.step==='draw')next=applyAction(next,p.id,{type:'draw',source:'deck'});for(let i=0;i<15&&next.status==='playing';i++){const moves=getValidMoves(next,p.id);const play=moves.find(m=>m.type==='phase'||m.type==='hit');if(!play)break;next=applyAction(next,p.id,play as Action);}if(next.status==='playing'){const hand=next.players.find(x=>x.id===p.id)!.hand;const player=next.players.find(x=>x.id===p.id)!;const ranked=shuffle(hand).map(card=>({card,progress:player.completed?0:phaseProgress(hand.filter(c=>c.id!==card.id),player.phase)}));ranked.sort((a,b)=>b.progress-a.progress||(a.card.color==='wild'?1:0)-(b.card.color==='wild'?1:0));const worst=ranked[0].card;next=applyAction(next,p.id,{type:'discard',cardId:worst.id});}return next;}
export function automaticTurnDue(g:Game,now=Date.now()){
 if(g.status!=='playing')return false;
 const p=g.players[g.turn];
 return (p.bot&&now-g.turnAt>1300)||(g.timer>0&&now-g.turnAt>=g.timer*1000)||(!p.bot&&now-p.lastSeen>90000);
}
export function advanceAutomaticTurn(g:Game,now=Date.now()):Game{
 if(!automaticTurnDue(g,now))return g;
 const player=g.players[g.turn];
 if(player.bot)return botTurn(g);
 const disconnected=now-player.lastSeen>90000,seen=player.lastSeen;
 let next=g.step==='draw'?applyAction(g,player.id,{type:'draw',source:'deck'}):g;
 const p=next.players[next.turn];
 next=applyAction(next,p.id,{type:'discard',cardId:p.hand.at(-1)!.id});
 if(disconnected)next.players.find(x=>x.id===p.id)!.lastSeen=seen;
 log(next,disconnected?`${p.name} is away. Their turn was played automatically.`:`${p.name}’s timer ended. A card was discarded automatically.`);
 return next;
}
